### ISSUE TITLE
Calculator cannot do decimals

### ISSUE THREAD

**Issue by Owen2k6** [Owen2k6/GoOS.old#1]
### **Known issue:**

**OS crashes when attempting to perform a calculation that contains a decimal number.**

**Comment by Owen2k6** [comment]
Disabled Calculator until i can make something work...

**Comment by valvhammer** [comment]
Easy fix:make the input variables a float, because floats have decimals in it

Plus dont store the output(aka answer) into a variable, just print it out

**Comment by Owen2k6** [comment]
> Easy fix:make the input variables a float, because floats have decimals in it
> 
> Plus dont store the output(aka answer) into a variable, just print it out

Thank you! i will implement it into the next version!

**Comment by Owen2k6** [comment]
float caused a cpu error when inputting a decimal place

**Comment by Owen2k6** [comment]
![image](https://user-images.githubusercontent.com/77968974/127712953-c52937dc-b86e-4c4b-9e15-f6599fa43711.png)

@AnonimFan  this is the error shown by the handler

**Comment by valvhammer** [comment]
try doubles

**Comment by Owen2k6** [comment]
I was able to fix it. The original code was converting the input to int32. So I changed it to convert to float.
